sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: nightly

env:
  global:
    - THEME_DIR=./web/app/themes/foundation/

before_install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install -g npm@2 gulp bower
  - bundle install

install:
  - composer install --no-dev --no-scripts --quiet --optimize-autoloader
  - cd $THEME_DIR
  - npm install --devDependencies --silent --no-spin
  - bower install
  - gulp --production

script:
  - cd $TRAVIS_BUILD_DIR
  - phpcs --standard=ruleset.xml --extensions=php --ignore=web/wp/,web/app/plugins/*,vendor/* -n -s .

cache:
  directories:
    - node_modules
